### ISSUE TITLE
Get Started button doesn't respond to click

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/jobcentre-pages#7]
## Problem
This button doesn't respond to clicks:
![image](https://user-images.githubusercontent.com/504505/52892995-d9088300-314c-11e9-83b5-e010f13cb0e5.png)

## Reproduce
* Go here: https://get.bcjobs.ca/7-day-trial-w
* Scroll down to **Résumé Search** section
* Try clicking the **Get Started** button

**Comment by josephcoombes** [comment]
Fixed here: https://github.com/bcjobs/jobcentre-pages/commit/09e88031218e877230efaf32ca0cac6f95ecb6b3
